# Generated by Django 5.1.6 on 2025-02-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.RemoveField(
            model_name='template',
            name='url',
        ),
        migrations.AddField(
            model_name='template',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='template_files'),
        ),
    ]
