# Generated by Django 5.1.6 on 2025-02-20 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magenta', '0002_alter_category_options_alter_template_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
