# Generated by Django 5.1.6 on 2025-02-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magenta', '0003_alter_template_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
