# Generated by Django 5.1.6 on 2025-03-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magenta', '0003_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
