# Generated by Django 5.1.6 on 2025-03-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magenta', '0004_template_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='image',
        ),
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='template_images')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Magenta.template')),
            ],
        ),
    ]
