# Generated by Django 5.1.6 on 2025-03-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magenta', '0005_remove_template_image_templateimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='template_videos'),
        ),
    ]
