# Generated by Django 5.1.6 on 2025-04-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magenta', '0006_template_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='category_images'),
            preserve_default=False,
        ),
    ]
