# Generated by Django 5.1.6 on 2025-04-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magenta', '0007_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='sub_category_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.FileField(default=1, upload_to='template_files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='video',
            field=models.FileField(upload_to='template_videos'),
        ),
    ]
